export const products = [
  {
    id: 1,
    name: "Germany",
    native: "Belgin",
    population: "81.770.900",
    region: "Europe",
    sub_region: 0,
    capital: "Brussels",
    top_level: ".be",
    currencies: "Euro",
    languages: ["Dutch", "French", "German"],
    border_countries: ["France", "Germany", "Netheriands"],
    image: "/images/grmany.jpg",
  },
  {
    id: 2,
    name: "Brazil",
    native: "Belgin",
    population: "206.135.893",
    region: "Americas",
    sub_region: 0,
    capital: "Brasilia",
    top_level: ".be",
    currencies: "Euro",
    languages: ["Dutch", "French", "German"],
    border_countries: ["France", "Germany", "Netheriands"],
    image: "/images/brazil.jpg",
  },
  {
    id: 3,
    name: "Iceland",
    native: "Belgin",
    population: "334.300",
    region: "Europe",
    sub_region: 0,
    capital: "Reykjavik",
    top_level: ".be",
    currencies: "Euro",
    languages: ["Dutch", "French", "German"],
    border_countries: ["France", "Germany", "Netheriands"],
    image: "/images/iceland.jpg",
  },
  {
    id: 4,
    name: "Belgium",
    native: "Belgin",
    population: "11.319.511",
    region: "Europe",
    sub_region: 0,
    capital: "Brussels",
    top_level: ".be",
    currencies: "Euro",
    languages: ["Dutch", "French", "German"],
    border_countries: ["France", "Germany", "Netheriands"],
    image: "/images/afkan.jpg",
  },
  {
    id: 5,
    name: "Belgium",
    native: "Belgin",
    population: "11.319.511",
    region: "Europe",
    sub_region: 0,
    capital: "Brussels",
    top_level: ".be",
    currencies: "Euro",
    languages: ["Dutch", "French", "German"],
    border_countries: ["France", "Germany", "Netheriands"],
    image: "/images/aland.jpg",
  },
  {
    id: 6,
    name: "Belgium",
    native: "Belgin",
    population: "11.319.511",
    region: "Europe",
    sub_region: 0,
    capital: "Brussels",
    top_level: ".be",
    currencies: "Euro",
    languages: ["Dutch", "French", "German"],
    border_countries: ["France", "Germany", "Netheriands"],
    image: "/images/albania.jpg",
  },
  {
    id: 7,
    name: "Belgium",
    native: "Belgin",
    population: "11.319.511",
    region: "Europe",
    sub_region: 0,
    capital: "Brussels",
    top_level: ".be",
    currencies: "Euro",
    languages: ["Dutch", "French", "German"],
    border_countries: ["France", "Germany", "Netheriands"],
    image: "/images/alg.jpg",
  },
  {
    id: 8,
    name: "United States Of Amerrica",
    native: "Belgin",
    population: "11.319.511",
    region: "Europe",
    sub_region: 0,
    capital: "Brussels",
    top_level: ".be",
    currencies: "Euro",
    languages: ["Dutch", "French", "German"],
    border_countries: ["France", "Germany", "Netheriands"],
    image: "/images/UK.jpg",
  },
];
